### ISSUE TITLE
Add eforms package

### ISSUE THREAD

**Issue by corny** [digineo/texd#138]
Please add the the [eforms package](https://ctan.org/pkg/eforms) to the docker image.

**Comment by dmke** [comment]
Neither the `eforms` package nor the `acrotex` bundle is available in the Debian sources.

I suggest you use `hyperref`:


```latex
\documentclass[a4paper,11pt]{article}
\usepackage{helvet}
\usepackage{hyperref}

\newdimen\longline
\longline=\textwidth
\advance\longline-4cm

\def\LayoutTextField#1#2{#2} % override default in hyperref

\def\lbl#1{\hbox to 4cm{#1\dotfill\strut}}%
\def\labelline#1#2{\lbl{#1}\vbox{\hbox{\TextField[name=#1,width=#2,borderwidth=0]{\null}}\kern0pt\hrule}}

\def\q#1{\hbox to \hsize{\labelline{#1}{\longline}}\vskip1.4ex}

\begin{document}
  \q{First Name}
  \q{Last Name}
  \q{Email}
\end{document}
```

![image](https://github.com/digineo/texd/assets/327411/88e82515-4949-4c35-a384-40472e283cab)


Above example is from https://tex.stackexchange.com/a/14845, see also [package documentation, section 9](http://mirrors.ctan.org/macros/latex/contrib/hyperref/doc/hyperref-doc.pdf#section.9).
